version: "3.8"

services:
  app:
    container_name: app
    build:
      dockerfile: ./app.Dockerfile
    restart: always
    ports:
      - '8070:8081'
    environment:
      spring.datasource.url: jdbc:mysql://liquibase-db:3306/LiquibaseBuiltMe
    networks:
      - the_royal_network
  mysql_db:
    container_name: liquibase-db
    image: mysql
    restart: always
    expose:
      - 3306
    ports:
      - '3506:3306'
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    volumes:
      - db_storage:/var/lib/mysql
      - ./_setup/database/initialize.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - the_royal_network
volumes:
  db_storage:
networks:
  the_royal_network: